# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/OSGeo4W/apps/qgis/python/plugins/wktraster/ui/DlgAddRasterLayer.ui'
#
# Created: Wed Apr 15 18:52:42 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DlgAddRasterLayer(object):
    def setupUi(self, DlgAddRasterLayer):
        DlgAddRasterLayer.setObjectName(_fromUtf8("DlgAddRasterLayer"))
        DlgAddRasterLayer.resize(745, 617)
        self.formLayout = QtGui.QFormLayout(DlgAddRasterLayer)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(DlgAddRasterLayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox = QtGui.QComboBox(DlgAddRasterLayer)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem)
        self.label_7 = QtGui.QLabel(DlgAddRasterLayer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.label_7)
        self.tableWidget = QtGui.QTableWidget(DlgAddRasterLayer)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.tableWidget)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.label_2 = QtGui.QLabel(DlgAddRasterLayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtGui.QLineEdit(DlgAddRasterLayer)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtGui.QLabel(DlgAddRasterLayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtGui.QLineEdit(DlgAddRasterLayer)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.label_8 = QtGui.QLabel(DlgAddRasterLayer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.label_8)
        self.tableWidget_2 = QtGui.QTableWidget(DlgAddRasterLayer)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.formLayout.setWidget(13, QtGui.QFormLayout.SpanningRole, self.tableWidget_2)
        self.selAllCheckBox = QtGui.QCheckBox(DlgAddRasterLayer)
        self.selAllCheckBox.setObjectName(_fromUtf8("selAllCheckBox"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.selAllCheckBox)
        self.contLinesCheckBox = QtGui.QCheckBox(DlgAddRasterLayer)
        self.contLinesCheckBox.setObjectName(_fromUtf8("contLinesCheckBox"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.contLinesCheckBox)
        self.buttonBox = QtGui.QDialogButtonBox(DlgAddRasterLayer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.SpanningRole, self.buttonBox)
        self.pushButton = QtGui.QPushButton(DlgAddRasterLayer)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.pushButton)

        self.retranslateUi(DlgAddRasterLayer)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DlgAddRasterLayer.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DlgAddRasterLayer.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgAddRasterLayer)

    def retranslateUi(self, DlgAddRasterLayer):
        DlgAddRasterLayer.setWindowTitle(_translate("DlgAddRasterLayer", "Load Postgis Raster layer", None))
        self.label.setText(_translate("DlgAddRasterLayer", "Postgis\' connection:", None))
        self.label_7.setText(_translate("DlgAddRasterLayer", "Available tables", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DlgAddRasterLayer", "Schema", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DlgAddRasterLayer", "Table", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DlgAddRasterLayer", "SRID", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DlgAddRasterLayer", "Pixel Type", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DlgAddRasterLayer", "Is external file", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DlgAddRasterLayer", "Is regular block", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("DlgAddRasterLayer", "Pixel size x ", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("DlgAddRasterLayer", "Pixel size y", None))
        self.label_2.setText(_translate("DlgAddRasterLayer", "Table name:", None))
        self.label_3.setText(_translate("DlgAddRasterLayer", "SQL Query:", None))
        self.label_8.setText(_translate("DlgAddRasterLayer", "Query Results", None))
        self.selAllCheckBox.setText(_translate("DlgAddRasterLayer", "select All", None))
        self.contLinesCheckBox.setText(_translate("DlgAddRasterLayer", "get countour lines too", None))
        self.pushButton.setText(_translate("DlgAddRasterLayer", "RUN SQL", None))

